# Welcome to Serverless!
#sudo sls deploy -s Hackathon


service: codepage-hackathon


frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  versionFunctions: false
  iam:
      role:
          statements:
            -   Effect: "Allow"
                Action:
                  - "s3:*"
                Resource: !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref InputFilesBucket
                    - /*
            -   Effect: Allow
                Action:
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                Resource:
                    - "*"
functions:
  getChallenge:
    handler: handler.getChallenge
    events:
      - http:
          path: /getChallenge/getChallenges
          method: get
  getTeam:
    handler: handler.getTeam
    events:
      - http:
          path: /getTeam/teamId/{teamId}
          method: get

  getInput:
    handler: handler.getInput
    events:
      - http:
          path: /getInput/inputId/{inputId}
          method: get
  isCorrect:
    handler: handler.isCorrect
    events:
      - http:
          path: /isCorrect/teamId/{teamId}/challengeId/{challengeId}/answer/{answer}
          method: get

  upLoadInput:
    handler: handler.upLoadInput
    events:
      - http:
          path: /upLoadInput
          method: post
          cors: true

  updateTeam:
    handler: handler.updateTeam
    events:
      - http:
          path: /updateTeam
          method: post
          cors: true

  postTeam:
    handler: handler.postTeam
    events:
      - http:
          path: /postTeam
          method: post
          cors: true


resources:
  Resources:

    UsersDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HackathonChallenges
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TeamsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HackathonTeams
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    InputFilesBucket:
      Type: AWS::S3::Bucket
